"""Recreated missing migration

Revision ID: 4c76614f8474
Revises: 
Create Date: 2024-05-01 01:19:49.280887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c76614f8474'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
